### ISSUE TITLE
ArrayOfReferenceNode doesn't use association managers

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#35]
From what I can tell, it doesn't look like an ```ArrayOfObjectNode``` makes use of a configured custom association manager.  Stepping through, it looks like when it sets up the ```multiValuedAccessor```, the ```accessorFactory``` doesn't refer to the other association managers configured in the context.  

But, I could be missing something too.  I'll try to come up with a test case for it, although may take a little bit before I have one ready for ya.

**Comment by mikesir87** [comment]
Just pushed a test case, which is being included in PR #34.  Looks to be an issue when using ```arrayOfReferences```.  I tested it out with ```arrayOfObjects``` and that works just fine.

**Comment by ceharris** [comment]
I deliberately didn't use an association manager for array-of-references because I couldn't think of a use case.  An association manager would typically be used to set an owner property on the associate. Since references aren't owned, it didn't seem like it would be useful to have an association manager involved. But your use case -- maintaining a running total -- seems like it could be fairly common.

Be advised, that when an array of references is updated, the algorithm is different than for array of objects.  It goes like this:

```
manager.clear()
for (MutableViewEntity entity : entities) {
  Object ref = referenceResolver.resolve(type, entity);
  manager.add(ref)
}
```

I.e. the collection contents are simply replaced with those specified in the view.  So your example manager should set the running total to zero and empty the products collection on `clear`

**Comment by mikesir87** [comment]
Thanks for the heads-up, as I wasn't aware that that's what it was doing.  I'll make sure I'm doing the right thing in my own managers too.

**Comment by ceharris** [comment]
You couldn't have been aware of it, since the association manager isn't yet being used for array of references.  :-)

The `ToManyAssociationManager` doesn't even have a `clear` method yet... it is declared on the `MultiValuedAccessor` interface only.  But when this issue is resolved, that's how it'll work.

**Comment by mikesir87** [comment]
Haha... duh.  I was wondering where the ```clear``` method was.  Guess this "brain" of mine isn't firing on all cylinders yet.  :)
