### ISSUE TITLE
Support reference from root

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#51]
Found a use-case for creating a reference from the root.  I'd like to have a resource that consumes a JSON model that looks like:

```json
{ 
    "id" : "aaaabbbb-cccc-dddd-eeee-111122223333" 
}
```

and be able to resolve the reference.  When I build the ViewApplicator and call resolve() on it, I get the following exception:

```
Caused by: org.soulwing.prospecto.api.ViewApplicatorException: root node type must be `reference`
	at org.soulwing.prospecto.runtime.applicator.ConcreteViewApplicator.resolve(ConcreteViewApplicator.java:153)
```

But, not sure how to have a root node type of reference.  Any pointers?

**Comment by ceharris** [comment]
I'm fairly certain that all of the necessary support is already there, just not exposed via API. I think I was just waiting for a reason to expose it.

To add it, you'll need to start by adding a `reference` method declaration to [ViewTemplateBuilderProvider] (https://github.com/soulwing/prospecto/blob/master/prospecto-api/src/main/java/org/soulwing/prospecto/spi/ViewTemplateBuilderProvider.java). Should be the same (except in name) as the existing `object` method declaration.  The implementation goes in [ConcreteViewTemplateBuilderProvider] (https://github.com/soulwing/prospecto/blob/master/prospecto-runtime/src/main/java/org/soulwing/prospecto/runtime/builder/ConcreteViewTemplateBuilderProvider.java) and will be almost identical to that for `object`, except that instead of `RootObjectNode`, you'll want `RootReferenceNode` (which doesn't exist yet). You could copy the `testObject` method in [ConcreteViewTemplateBuilderProviderTest] (https://github.com/soulwing/prospecto/blob/master/prospecto-runtime/src/test/java/org/soulwing/prospecto/runtime/builder/ConcreteViewTemplateBuilderProviderTest.java) and do a little _mutatis muntandis_ on it to test the newly added method. Of course it won't work yet, because we still need to define `RootReferenceNode`.

In the runtime's [template] (https://github.com/soulwing/prospecto/tree/master/prospecto-runtime/src/main/java/org/soulwing/prospecto/runtime/template) package, make a copy of `RootObjectNode`. Rename it as `RootReferenceNode`. Fix the javadoc comment for the class. It should extend `ConcreteReferenceNode`. There shouldn't be anything else to change in there.

The visitor implementation that constructs an applicator tree from a view template tree looks like it already knows what to do with a reference node, no matter where it is in the tree, and the applicator's `resolve` method already does what you describe wanting to do. So I don't think anything else is needed to make this work.
