### ISSUE TITLE
Allow un-prettied JSON output

### ISSUE THREAD

**Issue by mikesir87** [soulwing/prospecto#54]
The `JsonViewWriter` currently uses a generator that is configured to always pretty print.  Although it _is_ pretty, it does increase payload size quite significantly for complex objects.  Would be nice to have a way to disable pretty printing.  

One idea is to disable pretty print by default and require configuration to re-enable it.  Since it doesn't change the output, I don't really consider that a backwards-compatibility issue.  You?

**Comment by ceharris** [comment]
Should be relatively easy to make it optional. Add a `WriterKeys` constant, use it to set the corresponding option when `JsonGeneratorFactory` is initialized. The static declaration for the generator will have to go... configuration options are an immutable characteristic of the generator factory. But I don't think it's very expensive to create the factory, so that's probably no big deal -- just create a factory in the `JsonViewWriter` constructor and discard it.

Make a PR and I'll merge it.
